//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticket_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public int IDEvents { get; set; }
        public string Title { get; set; }
        public int IDCategory { get; set; }
        public int NumbersOfVisitors { get; set; }
        public int IDOrganisation { get; set; }
        public string Status { get; set; }
        public int IDAuth { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    }
}
