//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticket_system
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ticket_Entities : DbContext
    {
        public Ticket_Entities()
            : base("name=Ticket_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authorization> Authorization { get; set; }
        public virtual DbSet<CategoriesEvents> CategoriesEvents { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Logging> Logging { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<Place> Place { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
        public virtual DbSet<TypeTicket> TypeTicket { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
