//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticket_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public int IDPlace { get; set; }
        public string Title { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
    }
}
